//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3_Verhicle_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyConversion
    {
        public int Id { get; set; }
        public decimal FromCurrency { get; set; }
        public decimal ToCurrency { get; set; }
        public Nullable<float> Ratio { get; set; }
    }
}
