//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProject3_Verhicle_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Images = new HashSet<Image>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Warehouses = new HashSet<Warehouse>();
        }
    
        public int Id { get; set; }
        public string VehicleName { get; set; }
        public int VehicleTypeId { get; set; }
        public int VehicleBrandId { get; set; }
        public string YearOfManufacture { get; set; }
        public Nullable<int> Seats { get; set; }
        public decimal Price { get; set; }
        public int VehicleStatus { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}
